### ISSUE TITLE
i got a error

### ISSUE THREAD

**Issue by YinBuLiao** [TheIgnorantDev/dmaApex#1]
E0325 C++ only allows inline specifiers in function declarations

**Comment by YinBuLiao** [comment]
![image](https://user-images.githubusercontent.com/35324248/233842282-4b8f1b59-9418-41b7-aaa6-a027b2b0a462.png)
![image](https://user-images.githubusercontent.com/35324248/233842290-2ae2a742-dc5a-4a75-8ced-f40731b3eb62.png)

**Comment by qhb1023** [comment]
serching in google ,easy to fix

**Comment by YinBuLiao** [comment]
i fixed it but i got a error can't create connector i'm using leetdma

**Comment by qhb1023** [comment]
[FTD3XX.zip](https://github.com/TheIgnorantDev/dmaApex/files/11304314/FTD3XX.zip)
try to put this dll with ur dmaApex.exe together

**Comment by YinBuLiao** [comment]
> [FTD3XX.zip](https://github.com/TheIgnorantDev/dmaApex/files/11304314/FTD3XX.zip) try to put this dll with ur dmaApex.exe together

I think we can add a contact to exchange about DMA, I see you are also Chinese

**Comment by TheIgnorantDev** [comment]
> [FTD3XX.zip](https://github.com/TheIgnorantDev/dmaApex/files/11304314/FTD3XX.zip) try to put this dll with ur dmaApex.exe together

This should fix your issue.

**Comment by qhb1023** [comment]
哈哈哈哈 忘记看你id了 我刚开始也连不上 后来我测速的时候发现多了这个dll 把这个dll和exe文件放一起就可以读写内存了 但是这个作者貌似还在解决基址问题 反正目前运行成功了也没效果 再等等吧
