### ISSUE TITLE
nothing happened

### ISSUE THREAD

**Issue by qhb1023** [TheIgnorantDev/dmaApex#2]
I'm successfully running it.But no glow or something in my game.Are the offsets going wrong?Here is my screenshot for the game and dma 
![123](https://user-images.githubusercontent.com/38847848/233852042-82f90869-9176-4a9c-86e8-2693a8679f2b.png)
![234](https://user-images.githubusercontent.com/38847848/233852047-53bcec4d-2016-4db3-9c16-d448c7f045f1.png)

**Comment by qhb1023** [comment]
![123](https://user-images.githubusercontent.com/38847848/233852070-969e0052-6608-45ee-bed9-7d1be06ab618.png)

**Comment by TheIgnorantDev** [comment]
Yes, This is an issue I'm facing right now. The last commit says that its not reading memory properly. From some reason in the new threads its not reusing a proper connection.

**Comment by qhb1023** [comment]
@TheIgnorantDev waiting for ur good news

**Comment by Alienccc** [comment]
现在还是不起作用- -

**Comment by ZeroArrayCPP** [comment]
> Yes, This is an issue I'm facing right now. The last commit says that its not reading memory properly. From some reason in the new threads its not reusing a proper connection.

I assume that you have not implemented read/write correctly, try using this template for reading
`template<typename T>
auto Memory::read(VMM_HANDLE x, uint64_t address) -> T
{
	T buffer;
	VMMDLL_MemRead(x, dwPID, address, PBYTE(&buffer), sizeof(T));
	return buffer;
}`

With it, I managed to read the value correctly.
I will be grateful if you continue to support the project. also try to change the recording method, I do not know if it works or not, that's what I use.
`template<typename T>
auto write(uint64_t address, T value) -> void
{
    VMMDLL_MemWrite(globals::hVMM, globals::qwID, address, PBYTE(&value), sizeof(T));
}`
